settings = {
    "scenarios": {
        "scenario_tau_0.5_u_85": {
            # General Settings:
            "bandwidth": 180e3,
            "frequency": 2600e6,
            "tx_power": 80,
            "number_of_slots": 2000,
            "slot_duration_in_seconds": 0.5e-3,
            "resource_blocks_per_slot": 5,

            # Proportional Fair:
            "ewma_time_constant": 0.5,
            "starvation_threshold": 5,

            "base_stations": [
                {"mode": "FIXED", "x": 49, "y": 27}
            ],
            "user_equipments": [
                {"mode": "FIXED", "x": 0, "y": 0, "number_of_ues": 1,"user_id": 'User-1'},
                {"mode": "FIXED", "x": 20, "y": 0, "number_of_ues": 1,"user_id": 'User-2'},
                {"mode": "FIXED", "x": 40, "y": 0, "number_of_ues": 1,"user_id": 'User-3'},
                {"mode": "FIXED", "x": 60, "y": 0, "number_of_ues": 1,"user_id": 'User-4'},
                {"mode": "FIXED", "x": 80, "y": 0, "number_of_ues": 1,"user_id": 'User-5'},
                {"mode": "FIXED", "x": 0, "y": 5, "number_of_ues": 1,"user_id": 'User-6'},
                {"mode": "FIXED", "x": 20, "y": 5, "number_of_ues": 1,"user_id": 'User-7'},
                {"mode": "FIXED", "x": 40, "y": 5, "number_of_ues": 1,"user_id": 'User-8'},
                {"mode": "FIXED", "x": 60, "y": 5, "number_of_ues": 1,"user_id": 'User-9'},
                {"mode": "FIXED", "x": 80, "y": 5, "number_of_ues": 1,"user_id": 'User-10'},
                {"mode": "FIXED", "x": 0, "y": 10, "number_of_ues": 1,"user_id": 'User-11'},
                {"mode": "FIXED", "x": 20, "y": 10, "number_of_ues": 1,"user_id": 'User-12'},
                {"mode": "FIXED", "x": 40, "y": 10, "number_of_ues": 1,"user_id": 'User-13'},
                {"mode": "FIXED", "x": 60, "y": 10, "number_of_ues": 1,"user_id": 'User-14'},
                {"mode": "FIXED", "x": 80, "y": 10, "number_of_ues": 1,"user_id": 'User-15'},
                {"mode": "FIXED", "x": 0, "y": 15, "number_of_ues": 1,"user_id": 'User-16'},
                {"mode": "FIXED", "x": 20, "y": 15, "number_of_ues": 1,"user_id": 'User-17'},
                {"mode": "FIXED", "x": 40, "y": 15, "number_of_ues": 1,"user_id": 'User-18'},
                {"mode": "FIXED", "x": 60, "y": 15, "number_of_ues": 1,"user_id": 'User-19'},
                {"mode": "FIXED", "x": 80, "y": 15, "number_of_ues": 1,"user_id": 'User-20'},
                {"mode": "FIXED", "x": 0, "y": 20, "number_of_ues": 1,"user_id": 'User-21'},
                {"mode": "FIXED", "x": 20, "y": 20, "number_of_ues": 1,"user_id": 'User-22'},
                {"mode": "FIXED", "x": 40, "y": 20, "number_of_ues": 1,"user_id": 'User-23'},
                {"mode": "FIXED", "x": 60, "y": 20, "number_of_ues": 1,"user_id": 'User-24'},
                {"mode": "FIXED", "x": 80, "y": 20, "number_of_ues": 1,"user_id": 'User-25'},
                {"mode": "FIXED", "x": 5, "y": 0, "number_of_ues": 1,"user_id": 'User-26'},
                {"mode": "FIXED", "x": 25, "y": 0, "number_of_ues": 1,"user_id": 'User-27'},
                {"mode": "FIXED", "x": 45, "y": 0, "number_of_ues": 1,"user_id": 'User-28'},
                {"mode": "FIXED", "x": 65, "y": 0, "number_of_ues": 1,"user_id": 'User-29'},
                {"mode": "FIXED", "x": 85, "y": 0, "number_of_ues": 1,"user_id": 'User-30'},
                {"mode": "FIXED", "x": 5, "y": 5, "number_of_ues": 1,"user_id": 'User-31'},
                {"mode": "FIXED", "x": 25, "y": 5, "number_of_ues": 1,"user_id": 'User-32'},
                {"mode": "FIXED", "x": 45, "y": 5, "number_of_ues": 1,"user_id": 'User-33'},
                {"mode": "FIXED", "x": 65, "y": 5, "number_of_ues": 1,"user_id": 'User-34'},
                {"mode": "FIXED", "x": 85, "y": 5, "number_of_ues": 1,"user_id": 'User-35'},
                {"mode": "FIXED", "x": 5, "y": 10, "number_of_ues": 1,"user_id": 'User-36'},
                {"mode": "FIXED", "x": 25, "y": 10, "number_of_ues": 1,"user_id": 'User-37'},
                {"mode": "FIXED", "x": 45, "y": 10, "number_of_ues": 1,"user_id": 'User-38'},
                {"mode": "FIXED", "x": 65, "y": 10, "number_of_ues": 1,"user_id": 'User-39'},
                {"mode": "FIXED", "x": 85, "y": 10, "number_of_ues": 1,"user_id": 'User-40'},
                {"mode": "FIXED", "x": 5, "y": 15, "number_of_ues": 1,"user_id": 'User-41'},
                {"mode": "FIXED", "x": 25, "y": 15, "number_of_ues": 1,"user_id": 'User-42'},
                {"mode": "FIXED", "x": 45, "y": 15, "number_of_ues": 1,"user_id": 'User-43'},
                {"mode": "FIXED", "x": 65, "y": 15, "number_of_ues": 1,"user_id": 'User-44'},
                {"mode": "FIXED", "x": 85, "y": 15, "number_of_ues": 1,"user_id": 'User-45'},
                {"mode": "FIXED", "x": 10, "y": 0, "number_of_ues": 1,"user_id": 'User-46'},
                {"mode": "FIXED", "x": 30, "y": 0, "number_of_ues": 1,"user_id": 'User-47'},
                {"mode": "FIXED", "x": 50, "y": 0, "number_of_ues": 1,"user_id": 'User-48'},
                {"mode": "FIXED", "x": 70, "y": 0, "number_of_ues": 1,"user_id": 'User-49'},
                {"mode": "FIXED", "x": 90, "y": 0, "number_of_ues": 1,"user_id": 'User-50'},
                {"mode": "FIXED", "x": 10, "y": 5, "number_of_ues": 1,"user_id": 'User-51'},
                {"mode": "FIXED", "x": 30, "y": 5, "number_of_ues": 1,"user_id": 'User-52'},
                {"mode": "FIXED", "x": 50, "y": 5, "number_of_ues": 1,"user_id": 'User-53'},
                {"mode": "FIXED", "x": 70, "y": 5, "number_of_ues": 1,"user_id": 'User-54'},
                {"mode": "FIXED", "x": 90, "y": 5, "number_of_ues": 1,"user_id": 'User-55'},
                {"mode": "FIXED", "x": 10, "y": 10, "number_of_ues": 1,"user_id": 'User-56'},
                {"mode": "FIXED", "x": 30, "y": 10, "number_of_ues": 1,"user_id": 'User-57'},
                {"mode": "FIXED", "x": 50, "y": 10, "number_of_ues": 1,"user_id": 'User-58'},
                {"mode": "FIXED", "x": 70, "y": 10, "number_of_ues": 1,"user_id": 'User-59'},
                {"mode": "FIXED", "x": 90, "y": 10, "number_of_ues": 1,"user_id": 'User-60'},
                {"mode": "FIXED", "x": 10, "y": 15, "number_of_ues": 1,"user_id": 'User-61'},
                {"mode": "FIXED", "x": 30, "y": 15, "number_of_ues": 1,"user_id": 'User-62'},
                {"mode": "FIXED", "x": 50, "y": 15, "number_of_ues": 1,"user_id": 'User-63'},
                {"mode": "FIXED", "x": 70, "y": 15, "number_of_ues": 1,"user_id": 'User-64'},
                {"mode": "FIXED", "x": 90, "y": 15, "number_of_ues": 1,"user_id": 'User-65'},
                {"mode": "FIXED", "x": 15, "y": 0, "number_of_ues": 1,"user_id": 'User-66'},
                {"mode": "FIXED", "x": 35, "y": 0, "number_of_ues": 1,"user_id": 'User-67'},
                {"mode": "FIXED", "x": 55, "y": 0, "number_of_ues": 1,"user_id": 'User-68'},
                {"mode": "FIXED", "x": 75, "y": 0, "number_of_ues": 1,"user_id": 'User-69'},
                {"mode": "FIXED", "x": 95, "y": 0, "number_of_ues": 1,"user_id": 'User-70'},
                {"mode": "FIXED", "x": 15, "y": 5, "number_of_ues": 1,"user_id": 'User-71'},
                {"mode": "FIXED", "x": 35, "y": 5, "number_of_ues": 1,"user_id": 'User-72'},
                {"mode": "FIXED", "x": 55, "y": 5, "number_of_ues": 1,"user_id": 'User-73'},
                {"mode": "FIXED", "x": 75, "y": 5, "number_of_ues": 1,"user_id": 'User-74'},
                {"mode": "FIXED", "x": 95, "y": 5, "number_of_ues": 1,"user_id": 'User-75'},
                {"mode": "FIXED", "x": 15, "y": 10, "number_of_ues": 1,"user_id": 'User-76'},
                {"mode": "FIXED", "x": 35, "y": 10, "number_of_ues": 1,"user_id": 'User-77'},
                {"mode": "FIXED", "x": 55, "y": 10, "number_of_ues": 1,"user_id": 'User-78'},
                {"mode": "FIXED", "x": 75, "y": 10, "number_of_ues": 1,"user_id": 'User-79'},
                {"mode": "FIXED", "x": 95, "y": 10, "number_of_ues": 1,"user_id": 'User-80'},
                {"mode": "FIXED", "x": 15, "y": 15, "number_of_ues": 1,"user_id": 'User-81'},
                {"mode": "FIXED", "x": 35, "y": 15, "number_of_ues": 1,"user_id": 'User-82'},
                {"mode": "FIXED", "x": 55, "y": 15, "number_of_ues": 1,"user_id": 'User-83'},
                {"mode": "FIXED", "x": 75, "y": 15, "number_of_ues": 1,"user_id": 'User-84'},
                {"mode": "FIXED", "x": 95, "y": 15, "number_of_ues": 1,"user_id": 'User-85'}
            ],
            "capacity_calculator": "ProportionalFairCapacityCalculator"
        },
        "scenario_tau_1_u_85": {
            # General Settings:
            "bandwidth": 180e3,
            "frequency": 2600e6,
            "tx_power": 80,
            "number_of_slots": 2000,
            "slot_duration_in_seconds": 0.5e-3,
            "resource_blocks_per_slot": 5,

            # Proportional Fair:
            "ewma_time_constant": 1,
            "starvation_threshold": 5,

            "base_stations": [
                {"mode": "FIXED", "x": 49, "y": 27}
            ],
            "user_equipments": [
                {"mode": "FIXED", "x": 0, "y": 0, "number_of_ues": 1,"user_id": 'User-1'},
                {"mode": "FIXED", "x": 20, "y": 0, "number_of_ues": 1,"user_id": 'User-2'},
                {"mode": "FIXED", "x": 40, "y": 0, "number_of_ues": 1,"user_id": 'User-3'},
                {"mode": "FIXED", "x": 60, "y": 0, "number_of_ues": 1,"user_id": 'User-4'},
                {"mode": "FIXED", "x": 80, "y": 0, "number_of_ues": 1,"user_id": 'User-5'},
                {"mode": "FIXED", "x": 0, "y": 5, "number_of_ues": 1,"user_id": 'User-6'},
                {"mode": "FIXED", "x": 20, "y": 5, "number_of_ues": 1,"user_id": 'User-7'},
                {"mode": "FIXED", "x": 40, "y": 5, "number_of_ues": 1,"user_id": 'User-8'},
                {"mode": "FIXED", "x": 60, "y": 5, "number_of_ues": 1,"user_id": 'User-9'},
                {"mode": "FIXED", "x": 80, "y": 5, "number_of_ues": 1,"user_id": 'User-10'},
                {"mode": "FIXED", "x": 0, "y": 10, "number_of_ues": 1,"user_id": 'User-11'},
                {"mode": "FIXED", "x": 20, "y": 10, "number_of_ues": 1,"user_id": 'User-12'},
                {"mode": "FIXED", "x": 40, "y": 10, "number_of_ues": 1,"user_id": 'User-13'},
                {"mode": "FIXED", "x": 60, "y": 10, "number_of_ues": 1,"user_id": 'User-14'},
                {"mode": "FIXED", "x": 80, "y": 10, "number_of_ues": 1,"user_id": 'User-15'},
                {"mode": "FIXED", "x": 0, "y": 15, "number_of_ues": 1,"user_id": 'User-16'},
                {"mode": "FIXED", "x": 20, "y": 15, "number_of_ues": 1,"user_id": 'User-17'},
                {"mode": "FIXED", "x": 40, "y": 15, "number_of_ues": 1,"user_id": 'User-18'},
                {"mode": "FIXED", "x": 60, "y": 15, "number_of_ues": 1,"user_id": 'User-19'},
                {"mode": "FIXED", "x": 80, "y": 15, "number_of_ues": 1,"user_id": 'User-20'},
                {"mode": "FIXED", "x": 0, "y": 20, "number_of_ues": 1,"user_id": 'User-21'},
                {"mode": "FIXED", "x": 20, "y": 20, "number_of_ues": 1,"user_id": 'User-22'},
                {"mode": "FIXED", "x": 40, "y": 20, "number_of_ues": 1,"user_id": 'User-23'},
                {"mode": "FIXED", "x": 60, "y": 20, "number_of_ues": 1,"user_id": 'User-24'},
                {"mode": "FIXED", "x": 80, "y": 20, "number_of_ues": 1,"user_id": 'User-25'},
                {"mode": "FIXED", "x": 5, "y": 0, "number_of_ues": 1,"user_id": 'User-26'},
                {"mode": "FIXED", "x": 25, "y": 0, "number_of_ues": 1,"user_id": 'User-27'},
                {"mode": "FIXED", "x": 45, "y": 0, "number_of_ues": 1,"user_id": 'User-28'},
                {"mode": "FIXED", "x": 65, "y": 0, "number_of_ues": 1,"user_id": 'User-29'},
                {"mode": "FIXED", "x": 85, "y": 0, "number_of_ues": 1,"user_id": 'User-30'},
                {"mode": "FIXED", "x": 5, "y": 5, "number_of_ues": 1,"user_id": 'User-31'},
                {"mode": "FIXED", "x": 25, "y": 5, "number_of_ues": 1,"user_id": 'User-32'},
                {"mode": "FIXED", "x": 45, "y": 5, "number_of_ues": 1,"user_id": 'User-33'},
                {"mode": "FIXED", "x": 65, "y": 5, "number_of_ues": 1,"user_id": 'User-34'},
                {"mode": "FIXED", "x": 85, "y": 5, "number_of_ues": 1,"user_id": 'User-35'},
                {"mode": "FIXED", "x": 5, "y": 10, "number_of_ues": 1,"user_id": 'User-36'},
                {"mode": "FIXED", "x": 25, "y": 10, "number_of_ues": 1,"user_id": 'User-37'},
                {"mode": "FIXED", "x": 45, "y": 10, "number_of_ues": 1,"user_id": 'User-38'},
                {"mode": "FIXED", "x": 65, "y": 10, "number_of_ues": 1,"user_id": 'User-39'},
                {"mode": "FIXED", "x": 85, "y": 10, "number_of_ues": 1,"user_id": 'User-40'},
                {"mode": "FIXED", "x": 5, "y": 15, "number_of_ues": 1,"user_id": 'User-41'},
                {"mode": "FIXED", "x": 25, "y": 15, "number_of_ues": 1,"user_id": 'User-42'},
                {"mode": "FIXED", "x": 45, "y": 15, "number_of_ues": 1,"user_id": 'User-43'},
                {"mode": "FIXED", "x": 65, "y": 15, "number_of_ues": 1,"user_id": 'User-44'},
                {"mode": "FIXED", "x": 85, "y": 15, "number_of_ues": 1,"user_id": 'User-45'},
                {"mode": "FIXED", "x": 10, "y": 0, "number_of_ues": 1,"user_id": 'User-46'},
                {"mode": "FIXED", "x": 30, "y": 0, "number_of_ues": 1,"user_id": 'User-47'},
                {"mode": "FIXED", "x": 50, "y": 0, "number_of_ues": 1,"user_id": 'User-48'},
                {"mode": "FIXED", "x": 70, "y": 0, "number_of_ues": 1,"user_id": 'User-49'},
                {"mode": "FIXED", "x": 90, "y": 0, "number_of_ues": 1,"user_id": 'User-50'},
                {"mode": "FIXED", "x": 10, "y": 5, "number_of_ues": 1,"user_id": 'User-51'},
                {"mode": "FIXED", "x": 30, "y": 5, "number_of_ues": 1,"user_id": 'User-52'},
                {"mode": "FIXED", "x": 50, "y": 5, "number_of_ues": 1,"user_id": 'User-53'},
                {"mode": "FIXED", "x": 70, "y": 5, "number_of_ues": 1,"user_id": 'User-54'},
                {"mode": "FIXED", "x": 90, "y": 5, "number_of_ues": 1,"user_id": 'User-55'},
                {"mode": "FIXED", "x": 10, "y": 10, "number_of_ues": 1,"user_id": 'User-56'},
                {"mode": "FIXED", "x": 30, "y": 10, "number_of_ues": 1,"user_id": 'User-57'},
                {"mode": "FIXED", "x": 50, "y": 10, "number_of_ues": 1,"user_id": 'User-58'},
                {"mode": "FIXED", "x": 70, "y": 10, "number_of_ues": 1,"user_id": 'User-59'},
                {"mode": "FIXED", "x": 90, "y": 10, "number_of_ues": 1,"user_id": 'User-60'},
                {"mode": "FIXED", "x": 10, "y": 15, "number_of_ues": 1,"user_id": 'User-61'},
                {"mode": "FIXED", "x": 30, "y": 15, "number_of_ues": 1,"user_id": 'User-62'},
                {"mode": "FIXED", "x": 50, "y": 15, "number_of_ues": 1,"user_id": 'User-63'},
                {"mode": "FIXED", "x": 70, "y": 15, "number_of_ues": 1,"user_id": 'User-64'},
                {"mode": "FIXED", "x": 90, "y": 15, "number_of_ues": 1,"user_id": 'User-65'},
                {"mode": "FIXED", "x": 15, "y": 0, "number_of_ues": 1,"user_id": 'User-66'},
                {"mode": "FIXED", "x": 35, "y": 0, "number_of_ues": 1,"user_id": 'User-67'},
                {"mode": "FIXED", "x": 55, "y": 0, "number_of_ues": 1,"user_id": 'User-68'},
                {"mode": "FIXED", "x": 75, "y": 0, "number_of_ues": 1,"user_id": 'User-69'},
                {"mode": "FIXED", "x": 95, "y": 0, "number_of_ues": 1,"user_id": 'User-70'},
                {"mode": "FIXED", "x": 15, "y": 5, "number_of_ues": 1,"user_id": 'User-71'},
                {"mode": "FIXED", "x": 35, "y": 5, "number_of_ues": 1,"user_id": 'User-72'},
                {"mode": "FIXED", "x": 55, "y": 5, "number_of_ues": 1,"user_id": 'User-73'},
                {"mode": "FIXED", "x": 75, "y": 5, "number_of_ues": 1,"user_id": 'User-74'},
                {"mode": "FIXED", "x": 95, "y": 5, "number_of_ues": 1,"user_id": 'User-75'},
                {"mode": "FIXED", "x": 15, "y": 10, "number_of_ues": 1,"user_id": 'User-76'},
                {"mode": "FIXED", "x": 35, "y": 10, "number_of_ues": 1,"user_id": 'User-77'},
                {"mode": "FIXED", "x": 55, "y": 10, "number_of_ues": 1,"user_id": 'User-78'},
                {"mode": "FIXED", "x": 75, "y": 10, "number_of_ues": 1,"user_id": 'User-79'},
                {"mode": "FIXED", "x": 95, "y": 10, "number_of_ues": 1,"user_id": 'User-80'},
                {"mode": "FIXED", "x": 15, "y": 15, "number_of_ues": 1,"user_id": 'User-81'},
                {"mode": "FIXED", "x": 35, "y": 15, "number_of_ues": 1,"user_id": 'User-82'},
                {"mode": "FIXED", "x": 55, "y": 15, "number_of_ues": 1,"user_id": 'User-83'},
                {"mode": "FIXED", "x": 75, "y": 15, "number_of_ues": 1,"user_id": 'User-84'},
                {"mode": "FIXED", "x": 95, "y": 15, "number_of_ues": 1,"user_id": 'User-85'}
            ],
            "capacity_calculator": "ProportionalFairCapacityCalculator"
        },
        "scenario_tau_1.5_u_85": {
            # General Settings:
            "bandwidth": 180e3,
            "frequency": 2600e6,
            "tx_power": 80,
            "number_of_slots": 2000,
            "slot_duration_in_seconds": 0.5e-3,
            "resource_blocks_per_slot": 5,

            # Proportional Fair:
            "ewma_time_constant": 1.5,
            "starvation_threshold": 5,

            "base_stations": [
                {"mode": "FIXED", "x": 49, "y": 27}
            ],
            "user_equipments": [
                {"mode": "FIXED", "x": 0, "y": 0, "number_of_ues": 1,"user_id": 'User-1'},
                {"mode": "FIXED", "x": 20, "y": 0, "number_of_ues": 1,"user_id": 'User-2'},
                {"mode": "FIXED", "x": 40, "y": 0, "number_of_ues": 1,"user_id": 'User-3'},
                {"mode": "FIXED", "x": 60, "y": 0, "number_of_ues": 1,"user_id": 'User-4'},
                {"mode": "FIXED", "x": 80, "y": 0, "number_of_ues": 1,"user_id": 'User-5'},
                {"mode": "FIXED", "x": 0, "y": 5, "number_of_ues": 1,"user_id": 'User-6'},
                {"mode": "FIXED", "x": 20, "y": 5, "number_of_ues": 1,"user_id": 'User-7'},
                {"mode": "FIXED", "x": 40, "y": 5, "number_of_ues": 1,"user_id": 'User-8'},
                {"mode": "FIXED", "x": 60, "y": 5, "number_of_ues": 1,"user_id": 'User-9'},
                {"mode": "FIXED", "x": 80, "y": 5, "number_of_ues": 1,"user_id": 'User-10'},
                {"mode": "FIXED", "x": 0, "y": 10, "number_of_ues": 1,"user_id": 'User-11'},
                {"mode": "FIXED", "x": 20, "y": 10, "number_of_ues": 1,"user_id": 'User-12'},
                {"mode": "FIXED", "x": 40, "y": 10, "number_of_ues": 1,"user_id": 'User-13'},
                {"mode": "FIXED", "x": 60, "y": 10, "number_of_ues": 1,"user_id": 'User-14'},
                {"mode": "FIXED", "x": 80, "y": 10, "number_of_ues": 1,"user_id": 'User-15'},
                {"mode": "FIXED", "x": 0, "y": 15, "number_of_ues": 1,"user_id": 'User-16'},
                {"mode": "FIXED", "x": 20, "y": 15, "number_of_ues": 1,"user_id": 'User-17'},
                {"mode": "FIXED", "x": 40, "y": 15, "number_of_ues": 1,"user_id": 'User-18'},
                {"mode": "FIXED", "x": 60, "y": 15, "number_of_ues": 1,"user_id": 'User-19'},
                {"mode": "FIXED", "x": 80, "y": 15, "number_of_ues": 1,"user_id": 'User-20'},
                {"mode": "FIXED", "x": 0, "y": 20, "number_of_ues": 1,"user_id": 'User-21'},
                {"mode": "FIXED", "x": 20, "y": 20, "number_of_ues": 1,"user_id": 'User-22'},
                {"mode": "FIXED", "x": 40, "y": 20, "number_of_ues": 1,"user_id": 'User-23'},
                {"mode": "FIXED", "x": 60, "y": 20, "number_of_ues": 1,"user_id": 'User-24'},
                {"mode": "FIXED", "x": 80, "y": 20, "number_of_ues": 1,"user_id": 'User-25'},
                {"mode": "FIXED", "x": 5, "y": 0, "number_of_ues": 1,"user_id": 'User-26'},
                {"mode": "FIXED", "x": 25, "y": 0, "number_of_ues": 1,"user_id": 'User-27'},
                {"mode": "FIXED", "x": 45, "y": 0, "number_of_ues": 1,"user_id": 'User-28'},
                {"mode": "FIXED", "x": 65, "y": 0, "number_of_ues": 1,"user_id": 'User-29'},
                {"mode": "FIXED", "x": 85, "y": 0, "number_of_ues": 1,"user_id": 'User-30'},
                {"mode": "FIXED", "x": 5, "y": 5, "number_of_ues": 1,"user_id": 'User-31'},
                {"mode": "FIXED", "x": 25, "y": 5, "number_of_ues": 1,"user_id": 'User-32'},
                {"mode": "FIXED", "x": 45, "y": 5, "number_of_ues": 1,"user_id": 'User-33'},
                {"mode": "FIXED", "x": 65, "y": 5, "number_of_ues": 1,"user_id": 'User-34'},
                {"mode": "FIXED", "x": 85, "y": 5, "number_of_ues": 1,"user_id": 'User-35'},
                {"mode": "FIXED", "x": 5, "y": 10, "number_of_ues": 1,"user_id": 'User-36'},
                {"mode": "FIXED", "x": 25, "y": 10, "number_of_ues": 1,"user_id": 'User-37'},
                {"mode": "FIXED", "x": 45, "y": 10, "number_of_ues": 1,"user_id": 'User-38'},
                {"mode": "FIXED", "x": 65, "y": 10, "number_of_ues": 1,"user_id": 'User-39'},
                {"mode": "FIXED", "x": 85, "y": 10, "number_of_ues": 1,"user_id": 'User-40'},
                {"mode": "FIXED", "x": 5, "y": 15, "number_of_ues": 1,"user_id": 'User-41'},
                {"mode": "FIXED", "x": 25, "y": 15, "number_of_ues": 1,"user_id": 'User-42'},
                {"mode": "FIXED", "x": 45, "y": 15, "number_of_ues": 1,"user_id": 'User-43'},
                {"mode": "FIXED", "x": 65, "y": 15, "number_of_ues": 1,"user_id": 'User-44'},
                {"mode": "FIXED", "x": 85, "y": 15, "number_of_ues": 1,"user_id": 'User-45'},
                {"mode": "FIXED", "x": 10, "y": 0, "number_of_ues": 1,"user_id": 'User-46'},
                {"mode": "FIXED", "x": 30, "y": 0, "number_of_ues": 1,"user_id": 'User-47'},
                {"mode": "FIXED", "x": 50, "y": 0, "number_of_ues": 1,"user_id": 'User-48'},
                {"mode": "FIXED", "x": 70, "y": 0, "number_of_ues": 1,"user_id": 'User-49'},
                {"mode": "FIXED", "x": 90, "y": 0, "number_of_ues": 1,"user_id": 'User-50'},
                {"mode": "FIXED", "x": 10, "y": 5, "number_of_ues": 1,"user_id": 'User-51'},
                {"mode": "FIXED", "x": 30, "y": 5, "number_of_ues": 1,"user_id": 'User-52'},
                {"mode": "FIXED", "x": 50, "y": 5, "number_of_ues": 1,"user_id": 'User-53'},
                {"mode": "FIXED", "x": 70, "y": 5, "number_of_ues": 1,"user_id": 'User-54'},
                {"mode": "FIXED", "x": 90, "y": 5, "number_of_ues": 1,"user_id": 'User-55'},
                {"mode": "FIXED", "x": 10, "y": 10, "number_of_ues": 1,"user_id": 'User-56'},
                {"mode": "FIXED", "x": 30, "y": 10, "number_of_ues": 1,"user_id": 'User-57'},
                {"mode": "FIXED", "x": 50, "y": 10, "number_of_ues": 1,"user_id": 'User-58'},
                {"mode": "FIXED", "x": 70, "y": 10, "number_of_ues": 1,"user_id": 'User-59'},
                {"mode": "FIXED", "x": 90, "y": 10, "number_of_ues": 1,"user_id": 'User-60'},
                {"mode": "FIXED", "x": 10, "y": 15, "number_of_ues": 1,"user_id": 'User-61'},
                {"mode": "FIXED", "x": 30, "y": 15, "number_of_ues": 1,"user_id": 'User-62'},
                {"mode": "FIXED", "x": 50, "y": 15, "number_of_ues": 1,"user_id": 'User-63'},
                {"mode": "FIXED", "x": 70, "y": 15, "number_of_ues": 1,"user_id": 'User-64'},
                {"mode": "FIXED", "x": 90, "y": 15, "number_of_ues": 1,"user_id": 'User-65'},
                {"mode": "FIXED", "x": 15, "y": 0, "number_of_ues": 1,"user_id": 'User-66'},
                {"mode": "FIXED", "x": 35, "y": 0, "number_of_ues": 1,"user_id": 'User-67'},
                {"mode": "FIXED", "x": 55, "y": 0, "number_of_ues": 1,"user_id": 'User-68'},
                {"mode": "FIXED", "x": 75, "y": 0, "number_of_ues": 1,"user_id": 'User-69'},
                {"mode": "FIXED", "x": 95, "y": 0, "number_of_ues": 1,"user_id": 'User-70'},
                {"mode": "FIXED", "x": 15, "y": 5, "number_of_ues": 1,"user_id": 'User-71'},
                {"mode": "FIXED", "x": 35, "y": 5, "number_of_ues": 1,"user_id": 'User-72'},
                {"mode": "FIXED", "x": 55, "y": 5, "number_of_ues": 1,"user_id": 'User-73'},
                {"mode": "FIXED", "x": 75, "y": 5, "number_of_ues": 1,"user_id": 'User-74'},
                {"mode": "FIXED", "x": 95, "y": 5, "number_of_ues": 1,"user_id": 'User-75'},
                {"mode": "FIXED", "x": 15, "y": 10, "number_of_ues": 1,"user_id": 'User-76'},
                {"mode": "FIXED", "x": 35, "y": 10, "number_of_ues": 1,"user_id": 'User-77'},
                {"mode": "FIXED", "x": 55, "y": 10, "number_of_ues": 1,"user_id": 'User-78'},
                {"mode": "FIXED", "x": 75, "y": 10, "number_of_ues": 1,"user_id": 'User-79'},
                {"mode": "FIXED", "x": 95, "y": 10, "number_of_ues": 1,"user_id": 'User-80'},
                {"mode": "FIXED", "x": 15, "y": 15, "number_of_ues": 1,"user_id": 'User-81'},
                {"mode": "FIXED", "x": 35, "y": 15, "number_of_ues": 1,"user_id": 'User-82'},
                {"mode": "FIXED", "x": 55, "y": 15, "number_of_ues": 1,"user_id": 'User-83'},
                {"mode": "FIXED", "x": 75, "y": 15, "number_of_ues": 1,"user_id": 'User-84'},
                {"mode": "FIXED", "x": 95, "y": 15, "number_of_ues": 1,"user_id": 'User-85'}
            ],
            "capacity_calculator": "ProportionalFairCapacityCalculator"
        },
        "scenario_tau_2_u_85": {
            # General Settings:
            "bandwidth": 180e3,
            "frequency": 2600e6,
            "tx_power": 80,
            "number_of_slots": 2000,
            "slot_duration_in_seconds": 0.5e-3,
            "resource_blocks_per_slot": 5,

            # Proportional Fair:
            "ewma_time_constant": 2,
            "starvation_threshold": 5,

            "base_stations": [
                {"mode": "FIXED", "x": 49, "y": 27}
            ],
            "user_equipments": [
                {"mode": "FIXED", "x": 0, "y": 0, "number_of_ues": 1,"user_id": 'User-1'},
                {"mode": "FIXED", "x": 20, "y": 0, "number_of_ues": 1,"user_id": 'User-2'},
                {"mode": "FIXED", "x": 40, "y": 0, "number_of_ues": 1,"user_id": 'User-3'},
                {"mode": "FIXED", "x": 60, "y": 0, "number_of_ues": 1,"user_id": 'User-4'},
                {"mode": "FIXED", "x": 80, "y": 0, "number_of_ues": 1,"user_id": 'User-5'},
                {"mode": "FIXED", "x": 0, "y": 5, "number_of_ues": 1,"user_id": 'User-6'},
                {"mode": "FIXED", "x": 20, "y": 5, "number_of_ues": 1,"user_id": 'User-7'},
                {"mode": "FIXED", "x": 40, "y": 5, "number_of_ues": 1,"user_id": 'User-8'},
                {"mode": "FIXED", "x": 60, "y": 5, "number_of_ues": 1,"user_id": 'User-9'},
                {"mode": "FIXED", "x": 80, "y": 5, "number_of_ues": 1,"user_id": 'User-10'},
                {"mode": "FIXED", "x": 0, "y": 10, "number_of_ues": 1,"user_id": 'User-11'},
                {"mode": "FIXED", "x": 20, "y": 10, "number_of_ues": 1,"user_id": 'User-12'},
                {"mode": "FIXED", "x": 40, "y": 10, "number_of_ues": 1,"user_id": 'User-13'},
                {"mode": "FIXED", "x": 60, "y": 10, "number_of_ues": 1,"user_id": 'User-14'},
                {"mode": "FIXED", "x": 80, "y": 10, "number_of_ues": 1,"user_id": 'User-15'},
                {"mode": "FIXED", "x": 0, "y": 15, "number_of_ues": 1,"user_id": 'User-16'},
                {"mode": "FIXED", "x": 20, "y": 15, "number_of_ues": 1,"user_id": 'User-17'},
                {"mode": "FIXED", "x": 40, "y": 15, "number_of_ues": 1,"user_id": 'User-18'},
                {"mode": "FIXED", "x": 60, "y": 15, "number_of_ues": 1,"user_id": 'User-19'},
                {"mode": "FIXED", "x": 80, "y": 15, "number_of_ues": 1,"user_id": 'User-20'},
                {"mode": "FIXED", "x": 0, "y": 20, "number_of_ues": 1,"user_id": 'User-21'},
                {"mode": "FIXED", "x": 20, "y": 20, "number_of_ues": 1,"user_id": 'User-22'},
                {"mode": "FIXED", "x": 40, "y": 20, "number_of_ues": 1,"user_id": 'User-23'},
                {"mode": "FIXED", "x": 60, "y": 20, "number_of_ues": 1,"user_id": 'User-24'},
                {"mode": "FIXED", "x": 80, "y": 20, "number_of_ues": 1,"user_id": 'User-25'},
                {"mode": "FIXED", "x": 5, "y": 0, "number_of_ues": 1,"user_id": 'User-26'},
                {"mode": "FIXED", "x": 25, "y": 0, "number_of_ues": 1,"user_id": 'User-27'},
                {"mode": "FIXED", "x": 45, "y": 0, "number_of_ues": 1,"user_id": 'User-28'},
                {"mode": "FIXED", "x": 65, "y": 0, "number_of_ues": 1,"user_id": 'User-29'},
                {"mode": "FIXED", "x": 85, "y": 0, "number_of_ues": 1,"user_id": 'User-30'},
                {"mode": "FIXED", "x": 5, "y": 5, "number_of_ues": 1,"user_id": 'User-31'},
                {"mode": "FIXED", "x": 25, "y": 5, "number_of_ues": 1,"user_id": 'User-32'},
                {"mode": "FIXED", "x": 45, "y": 5, "number_of_ues": 1,"user_id": 'User-33'},
                {"mode": "FIXED", "x": 65, "y": 5, "number_of_ues": 1,"user_id": 'User-34'},
                {"mode": "FIXED", "x": 85, "y": 5, "number_of_ues": 1,"user_id": 'User-35'},
                {"mode": "FIXED", "x": 5, "y": 10, "number_of_ues": 1,"user_id": 'User-36'},
                {"mode": "FIXED", "x": 25, "y": 10, "number_of_ues": 1,"user_id": 'User-37'},
                {"mode": "FIXED", "x": 45, "y": 10, "number_of_ues": 1,"user_id": 'User-38'},
                {"mode": "FIXED", "x": 65, "y": 10, "number_of_ues": 1,"user_id": 'User-39'},
                {"mode": "FIXED", "x": 85, "y": 10, "number_of_ues": 1,"user_id": 'User-40'},
                {"mode": "FIXED", "x": 5, "y": 15, "number_of_ues": 1,"user_id": 'User-41'},
                {"mode": "FIXED", "x": 25, "y": 15, "number_of_ues": 1,"user_id": 'User-42'},
                {"mode": "FIXED", "x": 45, "y": 15, "number_of_ues": 1,"user_id": 'User-43'},
                {"mode": "FIXED", "x": 65, "y": 15, "number_of_ues": 1,"user_id": 'User-44'},
                {"mode": "FIXED", "x": 85, "y": 15, "number_of_ues": 1,"user_id": 'User-45'},
                {"mode": "FIXED", "x": 10, "y": 0, "number_of_ues": 1,"user_id": 'User-46'},
                {"mode": "FIXED", "x": 30, "y": 0, "number_of_ues": 1,"user_id": 'User-47'},
                {"mode": "FIXED", "x": 50, "y": 0, "number_of_ues": 1,"user_id": 'User-48'},
                {"mode": "FIXED", "x": 70, "y": 0, "number_of_ues": 1,"user_id": 'User-49'},
                {"mode": "FIXED", "x": 90, "y": 0, "number_of_ues": 1,"user_id": 'User-50'},
                {"mode": "FIXED", "x": 10, "y": 5, "number_of_ues": 1,"user_id": 'User-51'},
                {"mode": "FIXED", "x": 30, "y": 5, "number_of_ues": 1,"user_id": 'User-52'},
                {"mode": "FIXED", "x": 50, "y": 5, "number_of_ues": 1,"user_id": 'User-53'},
                {"mode": "FIXED", "x": 70, "y": 5, "number_of_ues": 1,"user_id": 'User-54'},
                {"mode": "FIXED", "x": 90, "y": 5, "number_of_ues": 1,"user_id": 'User-55'},
                {"mode": "FIXED", "x": 10, "y": 10, "number_of_ues": 1,"user_id": 'User-56'},
                {"mode": "FIXED", "x": 30, "y": 10, "number_of_ues": 1,"user_id": 'User-57'},
                {"mode": "FIXED", "x": 50, "y": 10, "number_of_ues": 1,"user_id": 'User-58'},
                {"mode": "FIXED", "x": 70, "y": 10, "number_of_ues": 1,"user_id": 'User-59'},
                {"mode": "FIXED", "x": 90, "y": 10, "number_of_ues": 1,"user_id": 'User-60'},
                {"mode": "FIXED", "x": 10, "y": 15, "number_of_ues": 1,"user_id": 'User-61'},
                {"mode": "FIXED", "x": 30, "y": 15, "number_of_ues": 1,"user_id": 'User-62'},
                {"mode": "FIXED", "x": 50, "y": 15, "number_of_ues": 1,"user_id": 'User-63'},
                {"mode": "FIXED", "x": 70, "y": 15, "number_of_ues": 1,"user_id": 'User-64'},
                {"mode": "FIXED", "x": 90, "y": 15, "number_of_ues": 1,"user_id": 'User-65'},
                {"mode": "FIXED", "x": 15, "y": 0, "number_of_ues": 1,"user_id": 'User-66'},
                {"mode": "FIXED", "x": 35, "y": 0, "number_of_ues": 1,"user_id": 'User-67'},
                {"mode": "FIXED", "x": 55, "y": 0, "number_of_ues": 1,"user_id": 'User-68'},
                {"mode": "FIXED", "x": 75, "y": 0, "number_of_ues": 1,"user_id": 'User-69'},
                {"mode": "FIXED", "x": 95, "y": 0, "number_of_ues": 1,"user_id": 'User-70'},
                {"mode": "FIXED", "x": 15, "y": 5, "number_of_ues": 1,"user_id": 'User-71'},
                {"mode": "FIXED", "x": 35, "y": 5, "number_of_ues": 1,"user_id": 'User-72'},
                {"mode": "FIXED", "x": 55, "y": 5, "number_of_ues": 1,"user_id": 'User-73'},
                {"mode": "FIXED", "x": 75, "y": 5, "number_of_ues": 1,"user_id": 'User-74'},
                {"mode": "FIXED", "x": 95, "y": 5, "number_of_ues": 1,"user_id": 'User-75'},
                {"mode": "FIXED", "x": 15, "y": 10, "number_of_ues": 1,"user_id": 'User-76'},
                {"mode": "FIXED", "x": 35, "y": 10, "number_of_ues": 1,"user_id": 'User-77'},
                {"mode": "FIXED", "x": 55, "y": 10, "number_of_ues": 1,"user_id": 'User-78'},
                {"mode": "FIXED", "x": 75, "y": 10, "number_of_ues": 1,"user_id": 'User-79'},
                {"mode": "FIXED", "x": 95, "y": 10, "number_of_ues": 1,"user_id": 'User-80'},
                {"mode": "FIXED", "x": 15, "y": 15, "number_of_ues": 1,"user_id": 'User-81'},
                {"mode": "FIXED", "x": 35, "y": 15, "number_of_ues": 1,"user_id": 'User-82'},
                {"mode": "FIXED", "x": 55, "y": 15, "number_of_ues": 1,"user_id": 'User-83'},
                {"mode": "FIXED", "x": 75, "y": 15, "number_of_ues": 1,"user_id": 'User-84'},
                {"mode": "FIXED", "x": 95, "y": 15, "number_of_ues": 1,"user_id": 'User-85'}
            ],
            "capacity_calculator": "ProportionalFairCapacityCalculator"
        },
        "scenario_tau_2.5_u_85": {
            # General Settings:
            "bandwidth": 180e3,
            "frequency": 2600e6,
            "tx_power": 80,
            "number_of_slots": 2000,
            "slot_duration_in_seconds": 0.5e-3,
            "resource_blocks_per_slot": 5,

            # Proportional Fair:
            "ewma_time_constant": 2.5,
            "starvation_threshold": 5,

            "base_stations": [
                {"mode": "FIXED", "x": 49, "y": 27}
            ],
            "user_equipments": [
                {"mode": "FIXED", "x": 0, "y": 0, "number_of_ues": 1,"user_id": 'User-1'},
                {"mode": "FIXED", "x": 20, "y": 0, "number_of_ues": 1,"user_id": 'User-2'},
                {"mode": "FIXED", "x": 40, "y": 0, "number_of_ues": 1,"user_id": 'User-3'},
                {"mode": "FIXED", "x": 60, "y": 0, "number_of_ues": 1,"user_id": 'User-4'},
                {"mode": "FIXED", "x": 80, "y": 0, "number_of_ues": 1,"user_id": 'User-5'},
                {"mode": "FIXED", "x": 0, "y": 5, "number_of_ues": 1,"user_id": 'User-6'},
                {"mode": "FIXED", "x": 20, "y": 5, "number_of_ues": 1,"user_id": 'User-7'},
                {"mode": "FIXED", "x": 40, "y": 5, "number_of_ues": 1,"user_id": 'User-8'},
                {"mode": "FIXED", "x": 60, "y": 5, "number_of_ues": 1,"user_id": 'User-9'},
                {"mode": "FIXED", "x": 80, "y": 5, "number_of_ues": 1,"user_id": 'User-10'},
                {"mode": "FIXED", "x": 0, "y": 10, "number_of_ues": 1,"user_id": 'User-11'},
                {"mode": "FIXED", "x": 20, "y": 10, "number_of_ues": 1,"user_id": 'User-12'},
                {"mode": "FIXED", "x": 40, "y": 10, "number_of_ues": 1,"user_id": 'User-13'},
                {"mode": "FIXED", "x": 60, "y": 10, "number_of_ues": 1,"user_id": 'User-14'},
                {"mode": "FIXED", "x": 80, "y": 10, "number_of_ues": 1,"user_id": 'User-15'},
                {"mode": "FIXED", "x": 0, "y": 15, "number_of_ues": 1,"user_id": 'User-16'},
                {"mode": "FIXED", "x": 20, "y": 15, "number_of_ues": 1,"user_id": 'User-17'},
                {"mode": "FIXED", "x": 40, "y": 15, "number_of_ues": 1,"user_id": 'User-18'},
                {"mode": "FIXED", "x": 60, "y": 15, "number_of_ues": 1,"user_id": 'User-19'},
                {"mode": "FIXED", "x": 80, "y": 15, "number_of_ues": 1,"user_id": 'User-20'},
                {"mode": "FIXED", "x": 0, "y": 20, "number_of_ues": 1,"user_id": 'User-21'},
                {"mode": "FIXED", "x": 20, "y": 20, "number_of_ues": 1,"user_id": 'User-22'},
                {"mode": "FIXED", "x": 40, "y": 20, "number_of_ues": 1,"user_id": 'User-23'},
                {"mode": "FIXED", "x": 60, "y": 20, "number_of_ues": 1,"user_id": 'User-24'},
                {"mode": "FIXED", "x": 80, "y": 20, "number_of_ues": 1,"user_id": 'User-25'},
                {"mode": "FIXED", "x": 5, "y": 0, "number_of_ues": 1,"user_id": 'User-26'},
                {"mode": "FIXED", "x": 25, "y": 0, "number_of_ues": 1,"user_id": 'User-27'},
                {"mode": "FIXED", "x": 45, "y": 0, "number_of_ues": 1,"user_id": 'User-28'},
                {"mode": "FIXED", "x": 65, "y": 0, "number_of_ues": 1,"user_id": 'User-29'},
                {"mode": "FIXED", "x": 85, "y": 0, "number_of_ues": 1,"user_id": 'User-30'},
                {"mode": "FIXED", "x": 5, "y": 5, "number_of_ues": 1,"user_id": 'User-31'},
                {"mode": "FIXED", "x": 25, "y": 5, "number_of_ues": 1,"user_id": 'User-32'},
                {"mode": "FIXED", "x": 45, "y": 5, "number_of_ues": 1,"user_id": 'User-33'},
                {"mode": "FIXED", "x": 65, "y": 5, "number_of_ues": 1,"user_id": 'User-34'},
                {"mode": "FIXED", "x": 85, "y": 5, "number_of_ues": 1,"user_id": 'User-35'},
                {"mode": "FIXED", "x": 5, "y": 10, "number_of_ues": 1,"user_id": 'User-36'},
                {"mode": "FIXED", "x": 25, "y": 10, "number_of_ues": 1,"user_id": 'User-37'},
                {"mode": "FIXED", "x": 45, "y": 10, "number_of_ues": 1,"user_id": 'User-38'},
                {"mode": "FIXED", "x": 65, "y": 10, "number_of_ues": 1,"user_id": 'User-39'},
                {"mode": "FIXED", "x": 85, "y": 10, "number_of_ues": 1,"user_id": 'User-40'},
                {"mode": "FIXED", "x": 5, "y": 15, "number_of_ues": 1,"user_id": 'User-41'},
                {"mode": "FIXED", "x": 25, "y": 15, "number_of_ues": 1,"user_id": 'User-42'},
                {"mode": "FIXED", "x": 45, "y": 15, "number_of_ues": 1,"user_id": 'User-43'},
                {"mode": "FIXED", "x": 65, "y": 15, "number_of_ues": 1,"user_id": 'User-44'},
                {"mode": "FIXED", "x": 85, "y": 15, "number_of_ues": 1,"user_id": 'User-45'},
                {"mode": "FIXED", "x": 10, "y": 0, "number_of_ues": 1,"user_id": 'User-46'},
                {"mode": "FIXED", "x": 30, "y": 0, "number_of_ues": 1,"user_id": 'User-47'},
                {"mode": "FIXED", "x": 50, "y": 0, "number_of_ues": 1,"user_id": 'User-48'},
                {"mode": "FIXED", "x": 70, "y": 0, "number_of_ues": 1,"user_id": 'User-49'},
                {"mode": "FIXED", "x": 90, "y": 0, "number_of_ues": 1,"user_id": 'User-50'},
                {"mode": "FIXED", "x": 10, "y": 5, "number_of_ues": 1,"user_id": 'User-51'},
                {"mode": "FIXED", "x": 30, "y": 5, "number_of_ues": 1,"user_id": 'User-52'},
                {"mode": "FIXED", "x": 50, "y": 5, "number_of_ues": 1,"user_id": 'User-53'},
                {"mode": "FIXED", "x": 70, "y": 5, "number_of_ues": 1,"user_id": 'User-54'},
                {"mode": "FIXED", "x": 90, "y": 5, "number_of_ues": 1,"user_id": 'User-55'},
                {"mode": "FIXED", "x": 10, "y": 10, "number_of_ues": 1,"user_id": 'User-56'},
                {"mode": "FIXED", "x": 30, "y": 10, "number_of_ues": 1,"user_id": 'User-57'},
                {"mode": "FIXED", "x": 50, "y": 10, "number_of_ues": 1,"user_id": 'User-58'},
                {"mode": "FIXED", "x": 70, "y": 10, "number_of_ues": 1,"user_id": 'User-59'},
                {"mode": "FIXED", "x": 90, "y": 10, "number_of_ues": 1,"user_id": 'User-60'},
                {"mode": "FIXED", "x": 10, "y": 15, "number_of_ues": 1,"user_id": 'User-61'},
                {"mode": "FIXED", "x": 30, "y": 15, "number_of_ues": 1,"user_id": 'User-62'},
                {"mode": "FIXED", "x": 50, "y": 15, "number_of_ues": 1,"user_id": 'User-63'},
                {"mode": "FIXED", "x": 70, "y": 15, "number_of_ues": 1,"user_id": 'User-64'},
                {"mode": "FIXED", "x": 90, "y": 15, "number_of_ues": 1,"user_id": 'User-65'},
                {"mode": "FIXED", "x": 15, "y": 0, "number_of_ues": 1,"user_id": 'User-66'},
                {"mode": "FIXED", "x": 35, "y": 0, "number_of_ues": 1,"user_id": 'User-67'},
                {"mode": "FIXED", "x": 55, "y": 0, "number_of_ues": 1,"user_id": 'User-68'},
                {"mode": "FIXED", "x": 75, "y": 0, "number_of_ues": 1,"user_id": 'User-69'},
                {"mode": "FIXED", "x": 95, "y": 0, "number_of_ues": 1,"user_id": 'User-70'},
                {"mode": "FIXED", "x": 15, "y": 5, "number_of_ues": 1,"user_id": 'User-71'},
                {"mode": "FIXED", "x": 35, "y": 5, "number_of_ues": 1,"user_id": 'User-72'},
                {"mode": "FIXED", "x": 55, "y": 5, "number_of_ues": 1,"user_id": 'User-73'},
                {"mode": "FIXED", "x": 75, "y": 5, "number_of_ues": 1,"user_id": 'User-74'},
                {"mode": "FIXED", "x": 95, "y": 5, "number_of_ues": 1,"user_id": 'User-75'},
                {"mode": "FIXED", "x": 15, "y": 10, "number_of_ues": 1,"user_id": 'User-76'},
                {"mode": "FIXED", "x": 35, "y": 10, "number_of_ues": 1,"user_id": 'User-77'},
                {"mode": "FIXED", "x": 55, "y": 10, "number_of_ues": 1,"user_id": 'User-78'},
                {"mode": "FIXED", "x": 75, "y": 10, "number_of_ues": 1,"user_id": 'User-79'},
                {"mode": "FIXED", "x": 95, "y": 10, "number_of_ues": 1,"user_id": 'User-80'},
                {"mode": "FIXED", "x": 15, "y": 15, "number_of_ues": 1,"user_id": 'User-81'},
                {"mode": "FIXED", "x": 35, "y": 15, "number_of_ues": 1,"user_id": 'User-82'},
                {"mode": "FIXED", "x": 55, "y": 15, "number_of_ues": 1,"user_id": 'User-83'},
                {"mode": "FIXED", "x": 75, "y": 15, "number_of_ues": 1,"user_id": 'User-84'},
                {"mode": "FIXED", "x": 95, "y": 15, "number_of_ues": 1,"user_id": 'User-85'}
            ],
            "capacity_calculator": "ProportionalFairCapacityCalculator"
        },
        "scenario_tau_3_u_85": {
            # General Settings:
            "bandwidth": 180e3,
            "frequency": 2600e6,
            "tx_power": 80,
            "number_of_slots": 2000,
            "slot_duration_in_seconds": 0.5e-3,
            "resource_blocks_per_slot": 5,

            # Proportional Fair:
            "ewma_time_constant": 3,
            "starvation_threshold": 5,

            "base_stations": [
                {"mode": "FIXED", "x": 49, "y": 27}
            ],
            "user_equipments": [
                {"mode": "FIXED", "x": 0, "y": 0, "number_of_ues": 1,"user_id": 'User-1'},
                {"mode": "FIXED", "x": 20, "y": 0, "number_of_ues": 1,"user_id": 'User-2'},
                {"mode": "FIXED", "x": 40, "y": 0, "number_of_ues": 1,"user_id": 'User-3'},
                {"mode": "FIXED", "x": 60, "y": 0, "number_of_ues": 1,"user_id": 'User-4'},
                {"mode": "FIXED", "x": 80, "y": 0, "number_of_ues": 1,"user_id": 'User-5'},
                {"mode": "FIXED", "x": 0, "y": 5, "number_of_ues": 1,"user_id": 'User-6'},
                {"mode": "FIXED", "x": 20, "y": 5, "number_of_ues": 1,"user_id": 'User-7'},
                {"mode": "FIXED", "x": 40, "y": 5, "number_of_ues": 1,"user_id": 'User-8'},
                {"mode": "FIXED", "x": 60, "y": 5, "number_of_ues": 1,"user_id": 'User-9'},
                {"mode": "FIXED", "x": 80, "y": 5, "number_of_ues": 1,"user_id": 'User-10'},
                {"mode": "FIXED", "x": 0, "y": 10, "number_of_ues": 1,"user_id": 'User-11'},
                {"mode": "FIXED", "x": 20, "y": 10, "number_of_ues": 1,"user_id": 'User-12'},
                {"mode": "FIXED", "x": 40, "y": 10, "number_of_ues": 1,"user_id": 'User-13'},
                {"mode": "FIXED", "x": 60, "y": 10, "number_of_ues": 1,"user_id": 'User-14'},
                {"mode": "FIXED", "x": 80, "y": 10, "number_of_ues": 1,"user_id": 'User-15'},
                {"mode": "FIXED", "x": 0, "y": 15, "number_of_ues": 1,"user_id": 'User-16'},
                {"mode": "FIXED", "x": 20, "y": 15, "number_of_ues": 1,"user_id": 'User-17'},
                {"mode": "FIXED", "x": 40, "y": 15, "number_of_ues": 1,"user_id": 'User-18'},
                {"mode": "FIXED", "x": 60, "y": 15, "number_of_ues": 1,"user_id": 'User-19'},
                {"mode": "FIXED", "x": 80, "y": 15, "number_of_ues": 1,"user_id": 'User-20'},
                {"mode": "FIXED", "x": 0, "y": 20, "number_of_ues": 1,"user_id": 'User-21'},
                {"mode": "FIXED", "x": 20, "y": 20, "number_of_ues": 1,"user_id": 'User-22'},
                {"mode": "FIXED", "x": 40, "y": 20, "number_of_ues": 1,"user_id": 'User-23'},
                {"mode": "FIXED", "x": 60, "y": 20, "number_of_ues": 1,"user_id": 'User-24'},
                {"mode": "FIXED", "x": 80, "y": 20, "number_of_ues": 1,"user_id": 'User-25'},
                {"mode": "FIXED", "x": 5, "y": 0, "number_of_ues": 1,"user_id": 'User-26'},
                {"mode": "FIXED", "x": 25, "y": 0, "number_of_ues": 1,"user_id": 'User-27'},
                {"mode": "FIXED", "x": 45, "y": 0, "number_of_ues": 1,"user_id": 'User-28'},
                {"mode": "FIXED", "x": 65, "y": 0, "number_of_ues": 1,"user_id": 'User-29'},
                {"mode": "FIXED", "x": 85, "y": 0, "number_of_ues": 1,"user_id": 'User-30'},
                {"mode": "FIXED", "x": 5, "y": 5, "number_of_ues": 1,"user_id": 'User-31'},
                {"mode": "FIXED", "x": 25, "y": 5, "number_of_ues": 1,"user_id": 'User-32'},
                {"mode": "FIXED", "x": 45, "y": 5, "number_of_ues": 1,"user_id": 'User-33'},
                {"mode": "FIXED", "x": 65, "y": 5, "number_of_ues": 1,"user_id": 'User-34'},
                {"mode": "FIXED", "x": 85, "y": 5, "number_of_ues": 1,"user_id": 'User-35'},
                {"mode": "FIXED", "x": 5, "y": 10, "number_of_ues": 1,"user_id": 'User-36'},
                {"mode": "FIXED", "x": 25, "y": 10, "number_of_ues": 1,"user_id": 'User-37'},
                {"mode": "FIXED", "x": 45, "y": 10, "number_of_ues": 1,"user_id": 'User-38'},
                {"mode": "FIXED", "x": 65, "y": 10, "number_of_ues": 1,"user_id": 'User-39'},
                {"mode": "FIXED", "x": 85, "y": 10, "number_of_ues": 1,"user_id": 'User-40'},
                {"mode": "FIXED", "x": 5, "y": 15, "number_of_ues": 1,"user_id": 'User-41'},
                {"mode": "FIXED", "x": 25, "y": 15, "number_of_ues": 1,"user_id": 'User-42'},
                {"mode": "FIXED", "x": 45, "y": 15, "number_of_ues": 1,"user_id": 'User-43'},
                {"mode": "FIXED", "x": 65, "y": 15, "number_of_ues": 1,"user_id": 'User-44'},
                {"mode": "FIXED", "x": 85, "y": 15, "number_of_ues": 1,"user_id": 'User-45'},
                {"mode": "FIXED", "x": 10, "y": 0, "number_of_ues": 1,"user_id": 'User-46'},
                {"mode": "FIXED", "x": 30, "y": 0, "number_of_ues": 1,"user_id": 'User-47'},
                {"mode": "FIXED", "x": 50, "y": 0, "number_of_ues": 1,"user_id": 'User-48'},
                {"mode": "FIXED", "x": 70, "y": 0, "number_of_ues": 1,"user_id": 'User-49'},
                {"mode": "FIXED", "x": 90, "y": 0, "number_of_ues": 1,"user_id": 'User-50'},
                {"mode": "FIXED", "x": 10, "y": 5, "number_of_ues": 1,"user_id": 'User-51'},
                {"mode": "FIXED", "x": 30, "y": 5, "number_of_ues": 1,"user_id": 'User-52'},
                {"mode": "FIXED", "x": 50, "y": 5, "number_of_ues": 1,"user_id": 'User-53'},
                {"mode": "FIXED", "x": 70, "y": 5, "number_of_ues": 1,"user_id": 'User-54'},
                {"mode": "FIXED", "x": 90, "y": 5, "number_of_ues": 1,"user_id": 'User-55'},
                {"mode": "FIXED", "x": 10, "y": 10, "number_of_ues": 1,"user_id": 'User-56'},
                {"mode": "FIXED", "x": 30, "y": 10, "number_of_ues": 1,"user_id": 'User-57'},
                {"mode": "FIXED", "x": 50, "y": 10, "number_of_ues": 1,"user_id": 'User-58'},
                {"mode": "FIXED", "x": 70, "y": 10, "number_of_ues": 1,"user_id": 'User-59'},
                {"mode": "FIXED", "x": 90, "y": 10, "number_of_ues": 1,"user_id": 'User-60'},
                {"mode": "FIXED", "x": 10, "y": 15, "number_of_ues": 1,"user_id": 'User-61'},
                {"mode": "FIXED", "x": 30, "y": 15, "number_of_ues": 1,"user_id": 'User-62'},
                {"mode": "FIXED", "x": 50, "y": 15, "number_of_ues": 1,"user_id": 'User-63'},
                {"mode": "FIXED", "x": 70, "y": 15, "number_of_ues": 1,"user_id": 'User-64'},
                {"mode": "FIXED", "x": 90, "y": 15, "number_of_ues": 1,"user_id": 'User-65'},
                {"mode": "FIXED", "x": 15, "y": 0, "number_of_ues": 1,"user_id": 'User-66'},
                {"mode": "FIXED", "x": 35, "y": 0, "number_of_ues": 1,"user_id": 'User-67'},
                {"mode": "FIXED", "x": 55, "y": 0, "number_of_ues": 1,"user_id": 'User-68'},
                {"mode": "FIXED", "x": 75, "y": 0, "number_of_ues": 1,"user_id": 'User-69'},
                {"mode": "FIXED", "x": 95, "y": 0, "number_of_ues": 1,"user_id": 'User-70'},
                {"mode": "FIXED", "x": 15, "y": 5, "number_of_ues": 1,"user_id": 'User-71'},
                {"mode": "FIXED", "x": 35, "y": 5, "number_of_ues": 1,"user_id": 'User-72'},
                {"mode": "FIXED", "x": 55, "y": 5, "number_of_ues": 1,"user_id": 'User-73'},
                {"mode": "FIXED", "x": 75, "y": 5, "number_of_ues": 1,"user_id": 'User-74'},
                {"mode": "FIXED", "x": 95, "y": 5, "number_of_ues": 1,"user_id": 'User-75'},
                {"mode": "FIXED", "x": 15, "y": 10, "number_of_ues": 1,"user_id": 'User-76'},
                {"mode": "FIXED", "x": 35, "y": 10, "number_of_ues": 1,"user_id": 'User-77'},
                {"mode": "FIXED", "x": 55, "y": 10, "number_of_ues": 1,"user_id": 'User-78'},
                {"mode": "FIXED", "x": 75, "y": 10, "number_of_ues": 1,"user_id": 'User-79'},
                {"mode": "FIXED", "x": 95, "y": 10, "number_of_ues": 1,"user_id": 'User-80'},
                {"mode": "FIXED", "x": 15, "y": 15, "number_of_ues": 1,"user_id": 'User-81'},
                {"mode": "FIXED", "x": 35, "y": 15, "number_of_ues": 1,"user_id": 'User-82'},
                {"mode": "FIXED", "x": 55, "y": 15, "number_of_ues": 1,"user_id": 'User-83'},
                {"mode": "FIXED", "x": 75, "y": 15, "number_of_ues": 1,"user_id": 'User-84'},
                {"mode": "FIXED", "x": 95, "y": 15, "number_of_ues": 1,"user_id": 'User-85'}
            ],
            "capacity_calculator": "ProportionalFairCapacityCalculator"
        },
    }
}